from time import sleep
n = str(input('Digite seu nome completo: ')).strip()
nome = n.split()
print(f'Prazer em te conhecer !')
sleep(2)
print('Eu irei dizer seu primeiro e ultimo nome.')
sleep(1)
print('Primeiramente eu tenho que analisar ele..............')
sleep(1)
print('Analisando......')
sleep(1)
print('Analisando......')
sleep(1)
print(f'Seu primeiro nome é {nome[0]}')
print(f'E seu último nome é {nome[len(nome)-1]}')
