v = int(input('Digite o número que vocẽ quer ver a tabuada: '))

print('------------')
print(f'{v} * 1 = {v*1}')
print(f'{v} * 2 = {v*2}')
print(f'{v} * 3 = {v*3}')
print(f'{v} * 4 = {v*4}')
print(f'{v} * 5 = {v*5}')
print(f'{v} * 6 = {v*6}')
print(f'{v} * 7 = {v*7}')
print(f'{v} * 8 = {v*8}')
print(f'{v} * 8 = {v*9}')
print(f'{v} * 10 = {v*10}')
print('------------')
